### ISSUE TITLE
Utility for loading Nethack replay files for imitation learning?

### ISSUE THREAD

**Issue by Gregory-Eales** [facebookresearch/nle#111]
## 🚀 Feature / Question

I saw in the paper that NLE has the ability to replay games visually for agent diagnostics. Is there a way to easily load replay files from alt.org for imitation learning? If this isn't currently a feature, is it planned?

**Comment by rockt** [comment]
Hi @Gregory-Eales, this is indeed a planned feature. Note however that alt.org recordings do not contain the actions that human players have taken -- only the observations resulting from actions.

Cheers,
Tim

**Comment by actual-nh** [comment]
A few comments:
- Some variants have replay capabilities that include recordings of commands. FIQHack's [logreplay.c](https://github.com/FredrIQ/fiqhack/blob/development/libnethack/src/logreplay.c) appears to be the most developed for this purpose. [Nethack 4](https://github.com/tsadok/nethack4) and thus the derived [NethackFourk](https://github.com/tsadok/nhfourk/tree/bleeding-edge) may also be a possibility.
- Vanilla ttyreq files may actually still be of use, not so much for imitation learning (or forward/inverse dynamics), but for other varieties of encoding improvements, for instance - one could try to predict changes in status lines from other changes/messages, or predict changes in the map from messages.
- Do keep in mind conducts to determine how useful files will be. This would be particularly true for imitation learning, but also influences other uses - possible distortion of probabilities/circumstances of occurrence, particularly of screen information from things like Zen/Blind (or, for variants, permanent deafness or hallucination). (There are some conducts that should not be a problem, however, such as Survivor (explicit in some variants, but also detectable in vanilla), never having needed an amulet of life saving.) One rule of thumb might be allowing conducts found in both 50+% of ascensions in general and 50+% of ascensions of that particular role; this is a guess, however!
- Also keep in mind [start scumming](https://nethackwiki.com/wiki/Start_scumming). Escaped (other than "escaped in disgrace") may need to be excluded, and quits pretty definitely (for one thing, even if not start scumming, it may be very variable in quality of play - good until a, well, stupid mistake is made and the player quits in frustration). See the linked article for other considerations, such as role involvement (wizards) and one rule-of-thumb used to detect likely start scumming.

**Comment by actual-nh** [comment]
Oh - one other thought re conducts - keep in mind that an early-dying character may have some conducts intact that wouldn't have been kept if the character lasted longer. Illiterate - particularly for non-caster roles - would be an example. There are various filters one could use for this; for instance, if the character never encountered anything readable before dying, illiterate is meaningless. More general means of filtering would be on something like:
- game turns: anything intact after, say, 10,000 game turns is almost certainly intentional (10,000 is from the [speed ascension wiki page](https://nethackwiki.com/wiki/Speed_ascension));
- XL; or
- score: the ["beginner"](https://nethackwiki.com/wiki/Beginner) threshold may be a good place to start.
These can also be used for, say, adjusting observation distributions depending on [game stage](https://nethackwiki.com/wiki/Game_stages).

**Comment by condnsdmatters** [comment]
This is now released! Check the README.md for more info on the dataset!
