### ISSUE TITLE
Reconsider set_buffers and observation keys.

### ISSUE THREAD

**Issue by condnsdmatters** [facebookresearch/nle#133]
Currently `set_buffers` is part of an API that is callable at any time. This means that in theory, the buffers to which observations are written/read from can be changed mid environment run. It also means more observation types can be added mid run.

Maintaining this feature requires storing intermediate results in an intermediate class and writing to observation buffers once - something that is actually violated already by both the checks for `nle_get_obs()->screen_description` visible in PR #131, and in writing directly to the `observation` in PR #119 . However, both these violations are for important performance reasons.

We should consider making the `set_buffers` method private at all times, and ensuring observation keys and buffers can only be set once at creation. This would allow us to write directly to the observation buffer further down the line, which in turn should give us a performance boost.

**Comment by heiner** [comment]
> Maintaining this feature requires storing intermediate results in an intermediate class and writing to observation buffers once.

Can you elaborate? I'm happy to disable that "feature", but I'm not sure I understand how that would enable us to write into one less buffer?

**Comment by heiner** [comment]
I think I finally understood you point here. In fact, using `set_buffers` with an already started environment is currently broken, as e.g. `tty_chars`, `tty_cursor` will only update changes, not write the full observation every time. (I guess this could be fixed by writing the old data into the new buffer in `set_buffers`.)

What do you think is a good way to do this here? I don't think we can simply make `set_buffers` private in C++, as it is in fact called in nethack.py. We could add all its arguments to the constructor, but that would make things a bit cumbersome. How about we instead check in `set_buffers` if the environment has been started already (`if (nle_)`) and fail in that case?

**Comment by condnsdmatters** [comment]
Set buffers can now only be called once.   This ensures `tty_*` observations are safe from change buffers, and we could optimise remaining observations by removing one memcopy per observation_key per step (`glyphs`, `colors`, `screen_descriptions` etc...)

**Comment by condnsdmatters** [comment]
Closing - current set up is safe
