### ISSUE TITLE
Extract observations from ttyrec frames.

### ISSUE THREAD

**Issue by mwbyeon** [facebookresearch/nle#232]
For imitation learning, I read ttyrec files and convert to 2d array(24x80) like `tty_chars`.
But, cannot found code that extract observations(`glyphs, blstats, messages, inventory, ...`) from `tty_chars`.

How can we extract observations from a frame(`tty_chars`) in the same way as NLE?
or, Is there any idea(way) to solve this?

Thank you.

**Comment by heiner** [comment]
Hey MinWoo Byeon,

Thanks for your interest in NLE!

I don't think what you ask about is possible in general. E.g., for the tty output NLE uses, the inventory is only visible when it has been opened, so no good information can be inferred from the `tty_chars` output alone. For other output types, e.g., ncurses, parts of the inventory are visible at all times, but reliably processing those is going to prove tricky too.

The way NLE gets its feature observations is by accessing NetHack's internal game state as the game is running, which makes more information available than is contained in the raw output.

Training from ttyrec (e.g., alt.org's ~5M games) is a hard problem. We proposed NetHack as a challenge precisely because it proses "real-world" problems like this one.
