### ISSUE TITLE
How can I get current character's rol-rac-ali-gen combo for NetHackChallenge task?

### ISSUE THREAD

**Issue by adyomin** [facebookresearch/nle#233]
```
import gym  
import nle  
env = gym.make("NetHackChallenge-v0")  
print(env.character)  
```
Only prints "@".

Edit: If I understand correctly, text from taking action `Command.ATTRIBUTES` is not available via `obs` object atm.

**Comment by adyomin** [comment]
@condnsdmatters you [mentioned](https://github.com/facebookresearch/nle/pull/207#issuecomment-880796384) this issue recently:
>  While I appreciate that determining the race and role of your player might be useful to you, if you are looking for a more direct route in to getting this info you should open a different issue and we can discuss there.

Is there a more direct way of getting this info than parsing `Command.ATTRIBUTES` output once you complete the #207?

**Comment by paulkent-um** [comment]
Hi, fellow NLE botter here. One thing you can do as a stop-gap measure is use the tty_chars element in the observation, which contains the raw characters that would be displayed on the screen if a human were playing. This isn't a practical solution to all use-cases of #207 (notably, reading off lists of multiple items on a single space is impractical in this manner), but it should be workable for reading off Command.ATTRIBUTES since there's no danger of dungeon tiles being misinterpreted as part of the pop-up.

I have found success using this sort of technique to digest the output of the list of visible monsters (accessible with action 93: whatis, then action 55: "M").

**Comment by heiner** [comment]
Hey -- would `;` followed by `.` together with the alignment entry in the tty_chars work? E.g. `GLANCE` followed by `WAIT`? That gives a message like e.g. `@        a human or elf (human tourist called heiner)`. Unfortunately, blstats doesn't contain alignment, which really is an oversight on our part (#238), but you can find "neutral" etc in the actual bottom line entry in `tty_chars`:

```
Heiner the Rambler                St:10 Dx:15 Co:15 In:13 Wi:10 Ch:13 Neutral
Dlvl:1 $:428 HP:10(10) Pw:2(2) AC:10 Xp:1/0 T:2
```

**Comment by adyomin** [comment]
> would `;` followed by `.` ... work?  

It took me a moment to realize what this means! 

Thank you both @heiner and @paulkent-um! Both approaches provide a way to get what I was looking for!
