### ISSUE TITLE
more monsters exist than expected?

### ISSUE THREAD

**Issue by simiaolin** [facebookresearch/nle#354]
## 🚀 why there are more monsters than expected?

I was using Minihack, which is dependent on NLE. When I created an environment MinihackRoom, I set the number of monsters to be one. However, when I tried running the reinforcement learning task and visualizing it, sometimes I can set that there are two monsters. I attach the screenshots here. I am curious about the reason for it.

- In pixel

![image](https://user-images.githubusercontent.com/73182104/228836976-258c0e34-f97e-474d-81dd-61f9b2620434.png)

- In chars

![image](https://user-images.githubusercontent.com/73182104/228837008-51b98200-7f6f-4ab7-9df8-9123df74c2c9.png)

**Comment by condnsdmatters** [comment]
Hi there - a great question! My advice is you open this on the [Minihack repo](https://github.com/facebookresearch/minihack): CC @samvelyan

**Comment by samvelyan** [comment]
@simiaolin this is because the cave spiders are often generated in groups (see [nethack wiki](https://nethackwiki.com/wiki/Cave_spider)). If you definitely want only a single monster, you'd need to specify which monsters you want to generate on a slightly modified environment. Here is the monster difficulty you'd want to consider when spawning them: https://nethackwiki.com/wiki/Monster_difficulty. I'd start with the weakest ones.
