### ISSUE TITLE
Creating copy of the environment

### ISSUE THREAD

**Issue by Arqit** [facebookresearch/nle#91]
## 🐛 Bug

Upon trying to create a deep copy of the environment, the following error occurred: "TypeError: cannot pickle 'nle._pynethack.Nethack' object"

## To Reproduce

1. import gym
2. import nle
3. import copy as copy
4. env = gym.make("NetHackScore-v0")
5. env.reset()
6. env2 = copy.deepcopy(env)

Traceback (most recent call last):
  File "pract.py", line 7, in <module>
    env2 = copy.deepcopy(env)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/aq_/anaconda3/envs/nle/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'nle._pynethack.Nethack' object

## Expected behavior

Create a copy of the environment

## Environment
NLE version: 0.5.2
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.4

Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 455.23.04
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.2
[conda] Could not collect

**Comment by edran** [comment]
Hi @Arqit -- thank you for opening this issue.

I don't think we can easily support copying some of the environment's internal objects. What's the use case for it?

If you wish to have two identical environments, you could use the seeding system:

```python
import gym
import nle

env = gym.make("NetHackScore-v0")
env.reset()
seeds = env.get_seeds()

env2 = gym.make("netHackScore-v0")
env2.seed(*seeds)
env2.reset()
```

**Comment by heiner** [comment]
Hey Arqit,

That's a more than valid usecase. However, supporting it won't be as easy as calling `copy.deepcopy`. The underlying state of the nethack library NLE is using cannot be copied like that.

In my mind the best way to support your usecase would be to do what the NetHack community would call [Save Scumming](https://nethackwiki.com/wiki/Save_scumming), at scale. The flow would be along the lines of:

1. Send `S` and `y` to the game in order to save the current game state.
2. Copy the save file.
3. Restore it in several places.

This can work, but I suspect it doesn't currently. We can consider this issue a feature request to support that, but it's going to take us a bit as the whole team is generally a bit busy and we don't currently do research on search algorithms on NLE (although the idea is very promising!).

**Comment by Arqit** [comment]
Thank you for the suggested alternatives. Given the constraints, they will have to be the way forward for now and so I will close the issue.

**Comment by cerisara** [comment]
Sorry, but the get_seeds() and seed() trick does not work in my case: I've copy-pasted
your exact code, and render() both env and env2, and they're different !
Is there anything else to do ?
(I'm on ubuntu20)
