### ISSUE TITLE
libnethack

### ISSUE THREAD

**Issue by apowers313** [facebookresearch/nle#95]
## 🚀 Feature

Not a feature request so much as a heads up in case it's useful -- NetHack has a new [library](https://github.com/NetHack/NetHack/tree/NetHack-3.7/sys/libnh) compilation option (`make WANT_LIBNH=1`). Currently it compiles to a `.a` archive instead of a shared object, but I bet we could make a `.so` build target if you are interested.

## Motivation

* Removes the need for linking `ncurses`
* Adds fine-grained control over events using the [shim windowing interface](https://github.com/NetHack/NetHack/tree/NetHack-3.7/win/shim)
* Makes merging and maintenance easier

**Comment by heiner** [comment]
Hey Adam,

Thanks for letting us know, and thanks for your interest in our little project!

We will look into the changes for NH 3.7 when it officially released; we hope there's a number of things that might get easier than (e.g., the `PLAYAGAIN` feature to re-set the game state without reloading the game), and we also want to take a look into making use of the `Lua` interface for custom tasks.

I'll leave this task open to remind me of the `LIBNH` option.

**Comment by burgersmoke** [comment]
So it looks like this was completed, is that right? I assume so since it appears that NLE compiles a .so rather than .a.

**Comment by heiner** [comment]
It's right that we compile into a shared library now. We use dlopen/dlclose to re-set the state at the end of episodes (`PLAYAGAIN` would presumably help us not need to do that). We also dlopen/dlclose a _physical copy_ of the .so file in order to allow for different copies of NetHack to live within the same binary.

What we don't do, however, is to use the shim windowing interface or use the `LIBNH` option. Instead, we modify nethack to not include a `main()` function and still use the tty window interface (but got rid of ncurses by using NetHack's hardcoded `ANSI_DEFAULT` escape sequence definitions in termcap.c.

**Comment by burgersmoke** [comment]
Thank you @heiner .  I appreciate the additional explanation especially about the shim windowing and `LIBNH`.

**Comment by heiner** [comment]
Closing for now. Will revisit `WANT_LIBNH=1` when 3.7 is released.
